# Generated by Django 2.1.1 on 2019-06-16 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('item_desc', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('data_input', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('data_input', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('projeto_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('projeto_desc', models.CharField(max_length=100)),
                ('validade_date', models.DateField(auto_now_add=True)),
                ('data_input', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cnpj', models.BigIntegerField(primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=100)),
                ('empreendedor_flag', models.BooleanField(default=False)),
                ('data_input', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='cnpj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
        ),
        migrations.AddField(
            model_name='match',
            name='cnpj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
        ),
        migrations.AddField(
            model_name='match',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='projeto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Projeto'),
        ),
    ]
