# Generated by Django 2.1.1 on 2019-06-08 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaUsuario',
            fields=[
                ('conta_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('banco_id', models.IntegerField()),
                ('agencia_digito', models.IntegerField()),
                ('conta_digito', models.IntegerField()),
                ('poupanca_flag', models.BooleanField(default=False)),
                ('data_input', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorecido',
            fields=[
                ('favorecido_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('cpf_cnpj', models.BigIntegerField()),
                ('banco_id', models.IntegerField()),
                ('agencia_digito', models.IntegerField()),
                ('conta_digito', models.IntegerField()),
                ('poupanca_flag', models.BooleanField(default=False)),
                ('data_input', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('valor_dolar', models.FloatField()),
                ('dolar_conversao', models.FloatField()),
                ('data_input', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('transacao_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('valor_dolar', models.FloatField()),
                ('status_id', models.IntegerField()),
                ('data_input', models.DateTimeField(auto_now_add=True)),
                ('conta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ContaUsuario')),
                ('favorecido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Favorecido')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf_cnpj', models.BigIntegerField(primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=100)),
                ('cnpj_flag', models.BooleanField(default=False)),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_input', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='transacao_id_d2r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dolar', to='api.Transacao'),
        ),
        migrations.AddField(
            model_name='match',
            name='transacao_id_r2d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real', to='api.Transacao'),
        ),
        migrations.AddField(
            model_name='contausuario',
            name='cpf_cnpj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
        ),
    ]
