# Generated by Django 2.1.1 on 2019-06-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='infoUsuario',
            fields=[
                ('cnpj', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_abertura', models.DateField()),
                ('nome_empresarial', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=100)),
                ('data_input', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
