# Generated by Django 2.1.1 on 2019-06-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorecido',
            name='cpf_cnpj',
        ),
        migrations.AddField(
            model_name='favorecido',
            name='conta_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
