# Generated by Django 2.1.1 on 2019-06-09 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190608_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorecido',
            name='conta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ContaUsuario'),
        ),
    ]
