# Generated by Django 2.1.1 on 2019-06-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190608_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorecido',
            name='conta_id',
        ),
        migrations.AddField(
            model_name='favorecido',
            name='cpf_cnpj',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
