# Generated by Django 2.1.1 on 2019-06-09 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190609_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorecido',
            name='conta_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
            preserve_default=False,
        ),
    ]
