# Generated by Django 2.1.1 on 2019-06-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190609_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorecido',
            name='cnpj_flag',
            field=models.BooleanField(default=False),
        ),
    ]
